branches:
  only:
  - master
  - develop

language: node_js
node_js:
  - v6
  - v5
  - v4


before_script:
  - npm install -g gulp

script: gulp

deploy:
  provider: npm
  api_key: "$NPM_TOKEN"
  on:
    tags: true
